spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: testteasfjlasjfl123182739874397akjljsdfasdfasfwearqwe2345365373524gfadfdasdfasdf21324567afasdfasdfadft5fasdf
  redis-prefix-refresh: "test:dentruth:refreshToken:"
  access-token-expiration: 3600
  refresh-token-expiration: 3600
  token-type-claim: "token_type"
  access-token-type: "access"
  refresh-token-type: "refresh"

cloud:
  aws:
    s3:
      bucket: mock-bucket-name
    credentials:
      access-key: mock-access-key
      secret-key: mock-secret-key
    region:
      static: ap-northeast-2
    stack:
      auto: false

encryption:
  secret-key: 12345678901234567890123456789012
  iv: 1234567890123456

openai:
  api:
    key: test-key
  audio-model: whisper-1
  whisper-url: "https://api.openai.com/v1/audio/transcriptions"
  chat-model: gpt-4o-mini
  chat-url: "https://api.openai.com/v1/chat/completions"
  prompts:
    consultation-summary: 너는 치과 전문 상담 요약 AI야.
